dau: 
  - dau
duoi:
  - duoi
  - dui
dau-duoi:
  - dauduoi
  - dd
bao-lo:
  - bao 
  - lo
  - b 
  - bada 
  - baol 
  - balo 
  - blo
  - bao
  - ba
  - bl
  - baolo
  - bd
  - baodao
  - bdao
  - bld
  - bldao
  - daolo
xiu-chu:
  - xc
  - x
  - xiu
  - tl
  - dxc
  - xcd
  - xd
  - daoxc
  - xcdao
xiu-chu-dau:
  - xcdau
  - dauxc
  - xdau
xiu-chu-duoi:
  - xcduoi
  - duoixc
  - xcdui
  - xduoi
  - xdui
da:
  - da
  - dav
  - dv
  - d
  - dax
  - davg
  - davong
  - dth
  - dathang
  - thang
  - dat
  - dvong
  - dvog
  - davog
  - dav
  - da vong
  - da v
  - daxoay
  - da xoay
  - dacap
  - da cap
  - damoicap
  - vong da
  - vongda
