default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("PRIMARY_DATABASE_NAME") %>
  username: <%= ENV.fetch("PRIMARY_DATABASE_USER") %>
  password: <%= ENV.fetch("PRIMARY_DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("PRIMARY_DATABASE_HOST") %>

production:
  <<: *default
  database: production
  username: sample_postgres
  password:
